import type { ToolItem } from "@/types";

export const tools: ToolItem[] = [
  {
    title: "Merge PDF",
    description: "Combine multiple PDF files into one organized document.",
    href: "/tools/merge-pdf",
    badge: "Popular",
    icon: "merge",
    mode: "merge_pdf",
    accept: ".pdf,application/pdf",
    minFiles: 2,
    maxFiles: 12,
  },
  {
    title: "Split PDF",
    description: "Extract selected pages or split by custom ranges.",
    href: "/tools/split-pdf",
    badge: "Fast",
    icon: "split",
    mode: "split_pdf",
    accept: ".pdf,application/pdf",
    minFiles: 1,
    maxFiles: 1,
  },
  {
    title: "Compress PDF",
    description: "Reduce file size for quick sharing without heavy quality loss.",
    href: "/tools/compress-pdf",
    badge: "Light",
    icon: "compress",
    mode: "compress_pdf",
    accept: ".pdf,application/pdf",
    minFiles: 1,
    maxFiles: 1,
  },
  {
    title: "Image to PDF",
    description: "Convert JPG and PNG images into a clean PDF in seconds.",
    href: "/tools/image-to-pdf",
    badge: "Simple",
    icon: "image",
    mode: "image_to_pdf",
    accept: ".jpg,.jpeg,.png,image/jpeg,image/png",
    minFiles: 1,
    maxFiles: 20,
  },
  {
    title: "Word to PDF",
    description: "Turn DOC and DOCX files into print-ready PDF format.",
    href: "/tools/word-to-pdf",
    badge: "Reliable",
    icon: "word",
    mode: "word_to_pdf",
    accept: ".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    minFiles: 1,
    maxFiles: 1,
  },
  {
    title: "Protect PDF",
    description: "Add password protection to keep sensitive files private.",
    href: "/tools/protect-pdf",
    badge: "Secure",
    icon: "secure",
    mode: "protect_pdf",
    accept: ".pdf,application/pdf",
    minFiles: 1,
    maxFiles: 1,
  },
];
